export const technologies = [
  { value: 'HTML5', label: 'HTML5' },
  { value: 'CSS3', label: 'CSS3' },
  { value: 'SASS', label: 'SASS' },
  { value: 'Bootstrap', label: 'Bootstrap' },
  { value: 'Tailwind Css', label: 'Tailwind Css' },
  { value: 'Javascript', label: 'Javascript' },
  { value: 'Typescript', label: 'Typescript' },
  { value: 'Php', label: 'Php' },
  { value: 'Python', label: 'Python' },
  { value: 'Java', label: 'Java' },
  { value: 'Node.js', label: 'Node.js' },
  { value: 'Express.js', label: 'Express.js' },
  { value: 'Koa.js', label: 'Koa.js' },
  { value: 'React.js', label: 'React.js' },
  { value: 'Redux', label: 'Redux' },
  { value: 'GraphQL', label: 'GraphQL' },
  { value: 'Apollo', label: 'Apollo' },
  { value: 'Websocket/Socket.io', label: 'Websocket/Socket.io' },
  { value: 'Axios', label: 'Axios' },
  { value: 'Eslint', label: 'Eslint' },
  { value: 'Prettier', label: 'Prettier' },
  { value: 'Webpack', label: 'Webpack' },
  { value: 'Next.js', label: 'Next.js' },
  { value: 'Alpine.js', label: 'Alpine.js' },
  { value: 'MySQL', label: 'MySQL' },
  { value: 'MongoDB', label: 'MongoDB' },
  { value: 'Firebase', label: 'Firebase' },
  { value: 'Redis', label: 'Redis' },
  { value: 'Vercel', label: 'Vercel' },
  { value: 'Heroku', label: 'Heroku' },
  { value: 'Docker', label: 'Docker' },
  { value: 'Git', label: 'Git' },
  { value: 'Github', label: 'Github' },
  { value: 'GitLab', label: 'GitLab' },
  { value: 'GoogleCloud', label: 'GoogleCloud' },
  { value: 'GoogleAnalytics', label: 'GoogleAnalytics' },
  { value: 'Auth0', label: 'Auth0' },
  { value: 'PWA Studio', label: 'PWA Studio' },
];

export const devTechStack = [
  {
    Languages: ['Javascript', 'Java', 'Python', 'Php'],
  },
  {
    'Front-end': [
      'React.js',
      'Next.js',
      'Alpine.js',
      'HTML5',
      'Tailwind CSS',
      'SASS',
      'Material UI',
      'Zustand',
      'Redux',
      'Apollo GraphQL Client',
    ],
  },
  {
    'Back-end': [
      'Node.js',
      'Koa.js',
      'Express.js',
      'GraphQL',
      'Apollo GraphQL Server',
    ],
  },
  {
    Databases: ['MongoDB', 'MySQL', 'PostgreSQL', 'Firebase', 'Redis'],
  },
  {
    Git: ['Git', 'Github', 'GitLab'],
  },
  {
    'Web services': ['Vercel', 'Auth0', 'Heroku'],
  },
  {
    'CI/CD tools': ['Docker', 'Jenkins', 'GitLab'],
  },
  {
    eCommerce: ['Shopify', 'Magento 2', 'PWA Studio'],
  },
  {
    Other: ['Webpack', 'Websocket/Socket.io', 'Axios'],
  },
];
